name: Pulse-saas-platform-deploy

on:
  push:
    branches:
      - main
      - devops
      - monitoring


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env files
        run: |
          cp backend/.env.example backend/.env
          cp frontend/.env.example frontend/.env  


      - name: Build & push Docker backend image
        uses: docker/build-push-action@v5
        with:
          context: backend/
          file: backend/Dockerfile.backend
          push: true
          tags: abhilashr7/pulse-saas-platform-backend:lastest

      - name: Build & push Docker frontend image
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          file: frontend/Dockerfile.frontend
          push: true
          tags: abhilashr7/pulse-saas-platform-frontend:lastest

      # - name: Set up k8s
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.kubeconfig }}
      
      # - name: Deploy to Kubernetes
      #   run: |
      #       kubectl apply -f k8s/

      # - name: Verify Deployment
      #   run: |
      #     kubectl get pods -n app-namespace
          