name: Pulse-saas-platform-deploy

on:
  push:
    branches:
      - main
      - devops


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env files
        run: |
          cp backend/.env.example backend/.env
          cp frontend/.env.example frontend/.env  


      - name: Build and start services
        run: |
          docker compose up -d --build

      - name: Check services are running
        run: |
          docker ps

      - name: Verify Backend & Frontend Health
        run: |
          echo "Waiting for services to become available..."
          
          curl --retry 10 --retry-delay 3 --retry-all-errors --fail http://localhost:8000/ || {
            echo "Backend failed to respond!"
            docker compose logs backend
            exit 1
          }

          curl --retry 10 --retry-delay 3 --retry-all-errors --fail http://localhost:5173/ || {
            echo "Frontend failed to respond!"
            docker compose logs frontend
            exit 1
          }

      - name: Stop Services
        if: always()
        run: |
          docker compose down -v

  